query GetOpenOpportunities {
  allOpportunity(
    filters: { 
      status: "open", 
      earliest_start_date: {
        from: "2024-01-02", 
        to: "2024-12-20" 
      },
      latest_end_date: {
        from: "2024-01-02", 
        to: "2024-12-20"
      }
    }
  ) {
    data {
      id
      title
      programmes {
        short_name_display
      }
      branch {
        name
        company {
          name
          organisation_type {
            name
          }
        }
      }
      earliest_start_date
      latest_end_date
    }
  }
}
/*

Result:

{
  "data": {
    "allOpportunity": {
      "data": []
    }
  }
}

*/
